// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoDdx0865csr33yt2TzPum_RZ_2IkPRJI',
    appId: '1:890700743146:web:c3583e29ec4d55e1117293',
    messagingSenderId: '890700743146',
    projectId: 'flutter-mcd-firestore',
    authDomain: 'flutter-mcd-firestore.firebaseapp.com',
    storageBucket: 'flutter-mcd-firestore.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaMTZfByCsMeIExuhpnvmMeGtQ-XTAde0',
    appId: '1:890700743146:android:3875989d33b3a58e117293',
    messagingSenderId: '890700743146',
    projectId: 'flutter-mcd-firestore',
    storageBucket: 'flutter-mcd-firestore.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASoy1CMZ7R5sTlN4DcIZTM59dRHFg2Prg',
    appId: '1:890700743146:ios:c81a14b336013228117293',
    messagingSenderId: '890700743146',
    projectId: 'flutter-mcd-firestore',
    storageBucket: 'flutter-mcd-firestore.appspot.com',
    iosBundleId: 'com.example.flutterMcdEcommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASoy1CMZ7R5sTlN4DcIZTM59dRHFg2Prg',
    appId: '1:890700743146:ios:02f138396b64bc66117293',
    messagingSenderId: '890700743146',
    projectId: 'flutter-mcd-firestore',
    storageBucket: 'flutter-mcd-firestore.appspot.com',
    iosBundleId: 'com.example.flutterMcdEcommerce.RunnerTests',
  );
}
